### ISSUE TITLE
🐞 Compared to cram, prysk doesn't let me use .md files as tests

### ISSUE THREAD

**Issue by liskin** [prysk/prysk#224]
# Summary

Compared to cram, prysk doesn't let me use .md files as tests.

## Reproducing the Issue

Reproducibility: always

### Steps to reproduce the behavior:
1. `prysk tests/foo.md`

## Expected Behaviour
prysk uses foo.md as a test like cram always did

## Actual Behaviour
prysk prints "no tests found"

## Root Cause (optional)
Bisected to https://github.com/prysk/prysk/commit/d05aabc8f123213acc62e764d63cfa90e479254b

## Context
I've been using cram for years to make sure the examples in my README.md files are up to date.
See https://github.com/liskin/strava-gear/blob/be8dab8c5a3175e7861daf8e24e4b2605efbe50e/tests/readme/help.md and https://github.com/liskin/strava-gear/blob/be8dab8c5a3175e7861daf8e24e4b2605efbe50e/Makefile#L64-L76 for an example. Or https://github.com/liskin/liscopridge/blob/main/src/liscopridge/app/statshunters.md for why I really do need to keep it as .md, otherwise GitHub won't render it.
I'm trying to migrate to prysk but this is stopping me.

### System
**Desktop:**
 - OS: Debian testing
 - Python Version: 3.11
 - Package Version: 0.16.0 but I've bisected and believe everything since d05aabc8f123213acc62e764d63cfa90e479254b is affected

**Comment by Nicoretti** [comment]
Hi @liskin,

Thank you for bringing this issue to our attention. Your report highlights a use case that we hadn't on the radar. Your analysis, is spot-on (first thing which came to mind when reading the issue was `_findtests`). I fully support maintaining compatibility for such use cases, so I concur that this is a bug that needs to be addressed.

However, I must mention that my current schedule is quite packed, so I can't commit to an immediate fix. Rest assured, I will prioritize this issue and keep you updated on any progress directly within this thread.

Best regards,
Nico

**Comment by liskin** [comment]
Thanks for confirming that this is something worth addressing. I absolutely understand that you can't commit to fixing this soon—it's a hobby project and it's family holidays in many parts of the world.

I tried to implement a fix myself: https://github.com/prysk/prysk/pull/225
Take all the time you need to review it, switching my projects from cram to prysk isn't in any way urgent. 🙂

**Comment by Nicoretti** [comment]
@liskin just release [0.17.0](https://pypi.org/project/prysk/) thanks for the PR! 👍
